---
- name: Deploy Node Exporter
  hosts: your_target_servers
  become: yes
  vars:
    node_exporter_version: "0.18.1"  # Set the desired Node Exporter version
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    node_exporter_install_dir: "/opt/node_exporter"

  tasks:
    - name: Create Node Exporter user
      user:
        name: "{{ node_exporter_user }}"
        system: yes

    - name: Download and extract Node Exporter
      get_url:
        url: "{{ node_exporter_download_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"

    - name: Extract Node Exporter archive
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "{{ node_exporter_install_dir }}"
        remote_src: yes

    - name: Set ownership and permissions
      ansible.builtin.file:
        path: "{{ node_exporter_install_dir }}"
        recurse: yes
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"

    - name: Create systemd service
      ansible.builtin.template:
        src: node_exporter.service.j2
        dest: "/etc/systemd/system/node_exporter.service"
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
