---
- name: Deploy Node Exporter and Prometheus
  hosts: your_target_servers
  become: yes
  vars:
    node_exporter_version: "0.18.1"  # Set the desired Node Exporter version
    prometheus_version: "2.30.0"  # Set the desired Prometheus version
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    node_exporter_install_dir: "/opt/node_exporter"
    prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    prometheus_install_dir: "/opt/prometheus"

  tasks:
    - name: Create Node Exporter user
      user:
        name: "{{ node_exporter_user }}"
        system: yes

    - name: Download and extract Node Exporter
      get_url:
        url: "{{ node_exporter_download_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"

    - name: Extract Node Exporter archive
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "{{ node_exporter_install_dir }}"
        remote_src: yes

    - name: Set ownership and permissions for Node Exporter
      ansible.builtin.file:
        path: "{{ node_exporter_install_dir }}"
        recurse: yes
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"

    - name: Create systemd service for Node Exporter
      ansible.builtin.template:
        src: node_exporter.service.j2
        dest: "/etc/systemd/system/node_exporter.service"
      notify:
        - Reload systemd

    - name: Download and extract Prometheus
      get_url:
        url: "{{ prometheus_download_url }}"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"

    - name: Extract Prometheus archive
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "{{ prometheus_install_dir }}"
        remote_src: yes

    - name: Set ownership and permissions for Prometheus
      ansible.builtin.file:
        path: "{{ prometheus_install_dir }}"
        recurse: yes
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"

    - name: Create Prometheus configuration file
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_install_dir }}/prometheus.yml"
      notify:
        - Reload systemd

    - name: Create systemd service for Prometheus
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: "/etc/systemd/system/prometheus.service"
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - node_exporter
        - prometheus
